version: '3.8'

services:
  db1:
    image: mongo:latest
    container_name: db1
    ports:
      - "27017:27017"
    volumes:
      - C:/data/db1:/data/db
    command: ["mongod", "--port", "27017", "--dbpath", "/data/db", "--logpath", "/data/db/mongo.log", "--bind_ip", "0.0.0.0"]

  db2:
    image: mongo:latest
    container_name: db2
    ports:
      - "27018:27017"
    volumes:
      - C:/data/db2:/data/db
    command: ["mongod", "--port", "27017", "--dbpath", "/data/db", "--logpath", "/data/db/mongo.log", "--bind_ip", "0.0.0.0"]

  db3:
    image: mongo:latest
    container_name: db3
    ports:
      - "27019:27017"
    volumes:
      - C:/data/db3:/data/db
    command: ["mongod", "--port", "27017", "--dbpath", "/data/db", "--logpath", "/data/db/mongo.log", "--bind_ip", "0.0.0.0"]

  db4:
    image: mongo:latest
    container_name: db4
    ports:
      - "27020:27017"
    volumes:
      - C:/data/db4:/data/db
    command: ["mongod", "--port", "27017", "--dbpath", "/data/db", "--logpath", "/data/db/mongo.log", "--bind_ip", "0.0.0.0"]
